version: '3.8'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:debug reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/reservations/.env
    depends_on:
        - mongo
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:debug auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env
    depends_on:
        - mongo
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:

